/* Copyright (c) 2000-2006 ActiveState Software Inc.
   See the file LICENSE.txt for licensing information. */

#include "nsISupports.idl"

// Support for running the tutorials UI.

[scriptable, uuid(33c422ac-5482-4baa-8e44-fe013fce1cd3)]
interface koITutorialService : nsISupports {
    // Choose a suitable default working directory.
    wstring GetWorkingDir();
    // Create the working dir and load it with a working copy of the tutorial
    // files. Return an appropriate error message iff there was a problem.
    wstring PrepareWorkingDir(in wstring workingDir);
    // Project file name ralative to a working directory.
    attribute wstring projectFileName;
};


